### ISSUE TITLE
新建scratch-name

### ISSUE THREAD

**Issue by GosTopp** [wzpan/hexo-theme-wixo#21]
模版没有添加一个新的notebook的选项吗？

**configuration:**
```
rss: atom.xml
fancybox: true
favicon: favicon.png
inverse_sort: false
fold: true
google_analytics:
scratch_name: Scratch
search:
  path: search.xml
  field: all
```
怎么添加一个新的notebook类别？
谢谢！
